### ISSUE TITLE
Constant definitions not architecture independent

### ISSUE THREAD

**Issue by rikte88** [inotify-rs/inotify-sys#8]
Hi, I have an issue where using the inotify crate, an error is printed during init about invalid value passed to syscall.

I am using mips little endian, and looking at inotify.h i see:
/* Get the platform-dependent flags.  */
#include <bits/inotify.h>

I have verified that my correct flags for mips little endian are:
const IN_CLOEXEC : i32 = 0o02000000;
const IN_NONBLOCK : i32 = 0o00000200;

which differ from those in this crate. Would it be possible to pull in architecture independant values for these, maybe from the nix crate?

Br,
Karl

**Comment by hannobraun** [comment]
Hi @rikte88, thank you for bringing this to my attention! It's been a long time since I wrote this code and I don't even remember where I got these values.

> Would it be possible to pull in architecture independant values for these, maybe from the nix crate?

I'm not familiar with nix (beyond knowing that it exists), but that could certainly be a possibility. In any case, this is an issue that needs to be fixed, no matter what the solution ends up being.

I'll try to find the time to look into this soon, but that may not work out this week (hopefully next). I'll get to it sooner or later, but in the meantime, contributions would be very welcome.

**Comment by hannobraun** [comment]
Sorry for the long delay, @rikte88, but I finally got the chance to look into this. According to my research all constants except the two you mentioned should be the same on all platforms. The values for the platform-dependent constants can be taken from libc (`O_CLOEXEC` for `IN_CLOEXEC`, `O_NONBLOCK` for `IN_NONBLOCK`).

I've already merged a pull request that fixes this issue, but I don't have anything else than x86-64 available to test, so I can't verify that I fixed the issue. I did verify though that the values defined in libc for MIPS match the values that you've given here as correct.

@rikte88 Please verify that the issue is fixed for you in the master branch. If you can confirm that I got it right, I'd like to release a new version.

**Comment by rikte88** [comment]
Hi and thanks a lot for the update! I will be sure to test tomorrow and get
back to you with results. That was the last piece of the puzzle for us to
consider using Rust in production :) BR Karl

**Comment by hannobraun** [comment]
@rikte88 Have you had a chance to test the master branch?

**Comment by rikte88** [comment]
Hi, sorry I didn't have a chance to try it out as a lot of stuff landed on
my table before vacation, but I'll be back on Monday, I will be sure to try
it out on our mips and arm hardware.

BR
Karl

**Comment by hannobraun** [comment]
Thanks!
